age = int(input("What is your age? "))
ten = int(age + 10)
twenty = int(age + 20)
thirty = int(age + 30)
forty = int(age + 40)
print(f"You are {age} years old. ")
print(f"In 10 years, you will be {ten} years old. ")
print(f"In 20 years, you will be {twenty} years old. ")
print(f"In 30 years, you will be {thirty} years old. ")
print(f"In 40 years, you will be {forty} years old. ")